version: "3"
services:
  couchdb:
    image: couchdb:2.3
    container_name: couchdb
    ports:
      - 5984:5984
      - 4369:4369
      - 9100-9200:9100-9200
    volumes:
      - /home/vdb/couchdb/data:/opt/couchdb/data
      - /home/vdb/couchdb/etc/vm.args:/opt/couchdb/etc/vm.args
    environment:
      - COUCHDB_USER=group63
      - COUCHDB_PASSWORD=123